parameters:
  # Configure Cross-Site HTTP requests (CORS).
  # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS
  cors.config:
    enabled: true

    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders:
      - 'x-csrf-token'
      - 'content-type'
      - 'authorization'
      - 'origin'
      - 'accept'
      - 'x-requested-with'

    # Specify allowed request methods, specify ['*'] to allow all possible ones.
    allowedMethods: ["*"]

    # Configure requests allowed from specific origins.
    allowedOriginsPatterns:
      - '#somedomain\.com\.au$#'

    # Sets the Access-Control-Expose-Headers header.
    exposedHeaders: false

    # Sets the Access-Control-Max-Age header.
    maxAge: 86400

    # Sets the Access-Control-Allow-Credentials header.
    supportsCredentials: true
